SAMPLES, = glob_wildcards('../data/{sample}_1.fq')
# this rule determine the out put of this run
rule targets:
    input:
        expand("{sample}.cutadapt.sam", sample = SAMPLES),
        expand("{sample}.cutadapt.bam", sample = SAMPLES),
        expand("{sample}_transcript.gtf", sample = SAMPLES)
# calling the helper script therest.smk
include: "therest.smk"

