channels:
  - conda-forge
  - bioconda
  - main
  - r
dependencies:
  - snakemake-minimal =5.10.0
  - python =3.7.6
  - samtools =1.9
  - bowtie2 =2.3.5.1
  - hisat2 =2.2.0
  - stringtie =2.1.2
  - gffread =0.11.7
  - graphviz =2.42.3